# Generated by Django 4.2.7 on 2023-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='main/%Y/%m/%d')),
            ],
        ),
    ]
